### ISSUE TITLE
feat: 使用原子操作来优化性能

### ISSUE THREAD

**Issue by QingYi-Studio** [TYLDDB/TYLDDB-CSharp#3]
原子操作理论上可以获得更好的性能。

**Comment by TYLDDB** [comment]
@Grey-Wind Maybe we can use this.

**Comment by Grey-Wind** [comment]
> @Grey-Wind Maybe we can use this.

Sure.

**Comment by Grey-Wind** [comment]
https://github.com/TYLDDB/TYLDDB-CSharp/pull/4

Look this PR. Although it is a thread lock, it also has good performance.

**Comment by TYLDDB** [comment]
在多次测试下，已达到能力范围内的性能瓶颈，故快速缓存的速度优化不在考虑继续进行。
